version: '3.8'

networks:
  async-net:
    driver: bridge

volumes:
  mysql_data:
  redis_data:

services:
  mysql:
    image: mysql:8.0
    container_name: async-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: asyncjobdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "admin", "-padmin123"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - async-net

  redis:
    image: redis:7-alpine
    container_name: async-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - async-net

  async-app:
    build: .
    container_name: async-app
    ports:
      - "8080:8080"
    environment:
      # Dùng tên service để kết nối nội bộ
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/asyncjobdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    volumes:
      - ./logs:/app/logs
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - async-net
  prometheus:
    image: prom/prometheus:latest
    container_name: async_prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - async-net
  loki:
    image: grafana/loki:latest
    container_name: async-loki
    ports:
      - "3100:3100"
    # Dùng cấu hình mặc định để tránh lỗi thiếu file local-config.yaml
    networks:
      - async-net

  promtail:
    image: grafana/promtail:latest
    container_name: async-promtail
    volumes:
      - ./logs:/var/log/app
      - ./promtail/promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - async-net

  grafana:
    image: grafana/grafana:latest
    container_name: async-grafana
    ports:
      - "3000:3000"
    networks:
      - async-net