version: '3.8'

networks:
  async-net:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
  ollama_data:

services:
  mysql:
    image: mysql:8.0
    container_name: async-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL}

    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "admin", "-padmin123"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - async-net

  redis:
    image: redis:7-alpine
    container_name: async-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - async-net

  async-app:
    build: .
    container_name: async-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    volumes:
      - ./logs:/app/logs
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      ollama:
        condition: service_started   # 👈 thêm
    networks:
      - async-net
  prometheus:
    image: prom/prometheus:latest
    container_name: async_prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - async-net
  loki:
    image: grafana/loki:latest
    container_name: async-loki
    ports:
      - "3100:3100"
    networks:
      - async-net

  promtail:
    image: grafana/promtail:latest
    container_name: async-promtail
    volumes:
      - ./logs:/var/log/app
      - ./promtail/promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - async-net

  grafana:
    image: grafana/grafana:latest
    container_name: async-grafana
    ports:
      - "3000:3000"
    networks:
      - async-net

  ollama:
    image: ollama/ollama:latest
    container_name: async-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: always
    networks:
      - async-net