spring:
  datasource:
    url: jdbc:mysql://localhost:3306/asyncjobdb
    username: admin
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

  # ── Mailtrap: inbox test email, đăng ký free tại mailtrap.io ──
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ee68c3357c9725   # ← thay bằng username từ Mailtrap
    password: fb2e83f24305a1   # ← thay bằng password từ Mailtrap
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Ho_Chi_Minh

server:
  port: 8080

# Cấu hình thư mục lưu file PDF
app:
  storage:
    pdf-dir: uploads/pdf
    base-url: http://localhost:8080/files

  email:
    from: "Async Job System <noreply@asyncjob.com>"




# Actuator — expose endpoint /actuator/prometheus
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    tags:
      application: async-job-system   # tag này xuất hiện trong mọi metric

logging:
  level:
    com.trongtin: DEBUG
  file:
    # Dùng đường dẫn tuyệt đối khớp với thư mục đã tạo trong Dockerfile
    name: /app/logs/spring-boot.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"