spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/asyncjobdb}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:admin123}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      connect-timeout: 5000ms
      timeout: 5000ms
      lettuce:
        shutdown-timeout: 200ms

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ${MAIL_USERNAME:ee68c3357c9725}
    password: ${MAIL_PASSWORD:fb2e83f24305a1}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Ho_Chi_Minh

server:
  port: 8080

app:
  storage:
    pdf-dir: uploads/pdf
    base-url: ${STORAGE_BASE_URL:http://localhost:8080/files}

  email:
    from: "Async Job System <noreply@asyncjob.com>"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    tags:
      application: async-job-system

logging:
  level:
    com.trongtin: DEBUG
  file:
    name: /app/logs/spring-boot.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# ── Cấu hình Ollama AI ──────────────────────────────
ollama:
  base-url:  ${OLLAMA_BASE_URL:http://localhost:11434}
  model: gemma3:4b
  enabled: true
  timeout-seconds: 120

resilience4j:
  circuitbreaker:
    instances:
      ollamaService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        #        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10

  ratelimiter:
    instances:
      createJob:
        limitForPeriod: 2
        limitRefreshPeriod: 10s
        timeoutDuration: 0
        registerHealthIndicator: true
        eventConsumerBufferSize: 100
      backendB:
        limitForPeriod: 5
        limitRefreshPeriod: 10s
        timeoutDuration: 3s