server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  # Phải trỏ về container 'loki' trong cùng mạng
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: spring-boot-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: async-job-system
          # Đường dẫn bên trong container Promtail (phải khớp volume trong compose)
          __path__: /var/log/app/*.log